<?php

/* watchdog hooking */
function drupal_gelf_watchdog(array $error) {
	/* get the config from drupal */
	$host = variable_get('drupal_gelf_host', 'localhost');
	$port = variable_get('drupal_gelf_port', '12201');
	/* format the packet from drupal error format */
	$errorPacket = drupal_gelf_format_error($error);
	/* chunk and send the GELF UDP packet */
	drupal_gelf_send_packet($host,$port,$errorPacket);
}

/* Should be self explainatory will do later : */
function drupal_gelf_help($path) {
	$message = "<h3>GELF logging enabled</h3>";
	$message .= "<p>GELF Logging is enabled and configured by your infrastructure team.</p>";
	$message .= "<pre>";
	$message .= "Host  : ".variable_get('drupal_gelf_host', 'localhost').PHP_EOL;
	$message .= "Port  : ".variable_get('drupal_gelf_port', '12345').PHP_EOL;
	$message .= "Group : ".variable_get('drupal_gelf_group', 'global').PHP_EOL;
	$message .= "</pre>";
	return $message;
}

// format an array with messages according GELF specs

function drupal_gelf_format_error(array $error) {
	//move all drupal stuff in _ (additionals for gelf)
	foreach($error as $error_key => $error_value) {
		unset($error[$error_key]);
		$error['_'.$error_key] = $error_value;
	}
	if(isset($error['_variables']) &&
	   is_array($error['_variables']) && 
	   !empty($error['_variables'])) {
	   $error['_message'] = str_replace(array_keys($error['_variables']), array_values($error['_variables']),$error['_message']);
	   foreach($error['_variables'] as $key => $variable) {
	   	$error['_'.str_replace('%','drupal_',$key)] = $variable;
	   }
	}
  	$error['_application'] = 'drupal_gelf';
  	
	$error['_log_group'] = variable_get('drupal_gelf_group', 'global');
  	$error['_website'] =  variable_get('site_name','localhost');
	//merge a formated GELF error + drupal error
	return array_merge(
		array(
		/* GELF required fields : */
		'version' => '1.1',
		'host' => gethostname(),
		'short_message' => $error['_message'],
		'level' => $error['_severity'],
		'timestamp' => time()
		),
		$error
	);
}


// generate an $max bytes unique BINARY string :
function drupal_gelf_get_unique_id($max) {
	$bytes = '';
	/* while not enough random bytes */
	while(strlen($bytes) < $max) {
		/* add one */
		$bytes .= chr(mt_rand(0,255));
	}
	/* and return the payload */
	return $bytes;
}

//Process the packet, chunk it and sends it
function drupal_gelf_send_packet($host,$port,array $error_event) {
	/* JSONify and compress the packet */
	$packet = gzcompress(json_encode($error_event));
	/* split it in max 512 bytes chunks, 512 will avoid packet getting drop on low MTUs */
	$chunks = str_split($packet,512); //512 is a safe value
	$total_chunks = count($chunks);
	$uniqid = drupal_gelf_get_unique_id(8);
	/* open a UDP sending socket */
	$socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
	/* and send packets 1 by 1, there's no support for non-chunked packet, who cares ? */
	foreach($chunks as $index => $chunk) {
    		//create UDP packet according GELF specs :
		$udpPacket =  implode('', array("\x1e\x0f" , $uniqid , chr($index) , chr($total_chunks) ,$chunk));
		//and send it :
		socket_sendto($socket, $udpPacket, strlen($udpPacket), 0, $host, $port);
	}
	socket_close($socket);
}

// Some settings for the backend
function drupal_gelf_form_system_logging_settings_alter(&$form, &$form_state) {
  $help = module_exists('help') ? ' ' . l(t('More information'), 'admin/help/drupal_gelf') . '.' : NULL;
  $form['drupal_gelf_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Remote GELF receiver'),
    '#default_value' => variable_get('drupal_gelf_host', 'localhost'),
    '#description' => t('Hostname or IP address of your Logstash/Graylog2 server.') . $help,
  );
  $form['drupal_gelf_port'] = array(
    '#type' => 'textfield',
    '#title' => t('Remote GELF receiver PORT'),
    '#default_value' => variable_get('drupal_gelf_port', '12201'),
    '#description' => t('Port on which your Logstash/Graylog2 instance is listening') . $help,
  );
  $form['drupal_gelf_group'] = array(
    '#type' => 'textfield',
    '#title' => t('Remote GELF receiver GROUP'),
    '#default_value' => variable_get('drupal_gelf_group', 'global'),
    '#description' => t('Sets a log_group variable to filter on in Logstash/Graylog2') . $help,
  );
  $form['actions']['#weight'] = 1;
}
